### ISSUE TITLE
[INFRA] Choose the hosting solution

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/process-analytics.dev#1]
We need a solution allowing us to use a custom domain (process-analytics.dev)

possible choices
- github-pages:
- netlify
- https://pages.cloudflare.com/ / https://developers.cloudflare.com/pages/
- ...

**Important**: impact of using custom domain with github-pages

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/about-custom-domains-and-github-pages#supported-custom-domains
> After you configure a custom domain for a user or organization site, the custom domain will replace the <user>.github.io or <organization>.github.io portion of the URL for any project sites owned by the account that do not have a custom domain configured. For example, if the custom domain for your user site is www.octocat.com, and you have a project site with no custom domain configured that is published from a repository called octo-project, the GitHub Pages site for that repository will be available at www.octocat.com/octo-project.

**Comment by csouchet** [comment]
If we choose Github pages, there is a gatsby plugin to do that: `gh-pages`
The official documentation: https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting/how-gatsby-works-with-github-pages/
The command to deploy: `gatsby build --prefix-paths && gh-pages -d public`
