### ISSUE TITLE
[FEAT] Include a testimonial on the Home page

### ISSUE THREAD

**Issue by csouchet** [process-analytics/process-analytics.dev#1091]
As the first user to recommend us, include the following testimonial: [https://www.bonitasoft.com/process-mining-AI?utm_source=ProcessAnalyticsWebsite&utm_medium=CTA&utm_campaign=ProcessAnalytics](https://www.bonitasoft.com/process-mining-AI?utm_source=ProcessAnalyticsWebsite&utm_medium=CTA&utm_campaign=ProcessAnalytics)  
  
### Inpiration

See **Trusted by over** section of https://demos.creative-tim.com/material-kit-react/#/presentation ([its code](https://github.com/creativetimofficial/material-kit-react/blob/main/src/pages/Presentation/sections/Testimonials.js)) and https://demos.creative-tim.com/material-kit-pro-react/#/sections/page-sections/logo-areas.

**Comment by csouchet** [comment]
Use something like https://demos.creative-tim.com/material-kit-pro-react/#/sections/page-sections/logo-areas

**Comment by tbouffard** [comment]
A mix of something like


![design_prop1](https://github.com/process-analytics/process-analytics.dev/assets/27200110/d18e6978-a732-4944-b36a-71c4010d7a36)


![design_prop2](https://github.com/process-analytics/process-analytics.dev/assets/27200110/9a402bf0-e33b-4728-b224-927ef5736ea0)
