### ISSUE TITLE
[BUG] Extra right banner on mobile

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/process-analytics.dev#945]
**Describe the bug**

**To Reproduce**
1. Go to the 'home' of https://process-analytics.dev/
2. Slide to the left or de-zoom

**Expected behavior**
We should not be able to slide or de-zoom, nor have the banner on the right side.

**Screenshots**

![image](https://user-images.githubusercontent.com/27200110/227874155-8311dd2a-9932-4f5b-b78a-fb3e7efea109.jpeg)

**Desktop (please complete the following information):**
 - OS: iOS 16.3.1, iPhone 8 
 - Browsers: Safari, Firefox 111.

**Comment by benjaminParisel** [comment]
Same issue on Android
OS:
Browsers: Chrome

![Screenshot_2023-03-27-09-59-01-952_com.android.chrome.jpg](https://user-images.githubusercontent.com/25297128/227878350-223155ed-4fa0-4433-b534-126307ed4405.jpg)

**Comment by tbouffard** [comment]
Not only on the beginning of the 

![image](https://user-images.githubusercontent.com/27200110/227880487-54cdf259-5cc1-497d-a6c8-4d2ae2db4cab.jpeg)
